#!/usr/bin/env bash

# This file can, but shouldn't need to be modified
# Set up autograder files

# Go to our directory (our current root) in the autograder
cd /autograder/source || {
  echo "Autograder source directory not found"
  exit 1
}

# Get a list of required files by looking at config.json
files_needed=$(python3 -c "
from processor import SubmissionProcessor as p

config = p.read_json('source', 'config.json')
print('\n'.join(config['files_needed']))
") || {
# If it fails, just return early
    echo "Error reading required files. Exiting."
    exit 1
}

# For each file (separated by a newline), copy it to source/files/ if present, otherwise just skip
IFS=$'\n'  # Delimiter
for file in $files_needed; do
    if [ -e "/autograder/submission/$file" ]; then
        cp "/autograder/submission/$file" "/autograder/source/files/$file"
    else
        echo "Warning: $file not found in /autograder/submission."
    fi
done
IFS=$original_ifs

# Finally, grade this submission
python3 run_tests.py
python3 processor.py
