#!/usr/bin/env bash

# Set up autograder files

files_needed=$(python3 -c "
from source.grader import Grader

config = Grader.read_json('source', 'config.json')
print(' '.join(config['files_needed']))
")

for file in $files_needed; do
    cp /autograder/submission/"$file" /autograder/source/"$file"
done

cd /autograder/source || exit 1

python3 run_tests.py
python3 grader.py
